export enum CategoriaRepuesto {
    MOTOR = 'MOTOR',
    FRENOS = 'FRENOS',
    SUSPENSION = 'SUSPENSION',
    TRANSMISION = 'TRANSMISION',
    ELECTRICO = 'ELECTRICO',
    CARROCERIA = 'CARROCERIA',
    INTERIOR = 'INTERIOR',
    ACCESORIOS = 'ACCESORIOS',
    SISTEMA_ENFRIAMIENTO = 'SISTEMA_ENFRIAMIENTO',
    ESCAPE = 'ESCAPE'
  }