export enum EstadoDetallado {
    PENDIENTE_INGRESO = 'PENDIENTE_INGRESO',
    EN_DIAGNOSTICO = 'EN_DIAGNOSTICO',
    ESPERANDO_REPUESTOS = 'ESPERANDO_REPUESTOS',
    EN_REPARACION = 'EN_REPARACION',
    EN_LAVADO = 'EN_LAVADO',
    EN_CONTROL_CALIDAD = 'EN_CONTROL_CALIDAD',
    LISTO_PARA_ENTREGAR = 'LISTO_PARA_ENTREGAR',
    ENTREGADO = 'ENTREGADO',
    CANCELADO = 'CANCELADO'
  }