export enum TipoNotificacion {
    RECORDATORIO_CITA = 'RECORDATORIO_CITA',
    SERVICIO_COMPLETADO = 'SERVICIO_COMPLETADO',
    CLIENTE_PREMIUM = 'CLIENTE_PREMIUM',
    SERVICIO_GRATIS_DISPONIBLE = 'SERVICIO_GRATIS_DISPONIBLE',
    CONTROL_CALIDAD = 'CONTROL_CALIDAD'
  }