export enum TipoServicio {
    LAVADO_BASICO = 'LAVADO_BASICO',
    LAVADO_COMPLETO = 'LAVADO_COMPLETO',
    LAVADO_PREMIUM = 'LAVADO_PREMIUM',
    ALINEACION_BALANCEO = 'ALINEACION_BALANCEO',
    ALINEACION_BALANCEO_CUBIERTAS = 'ALINEACION_BALANCEO_CUBIERTAS',
    CAMBIO_ACEITE_BASICO_NAFTA = 'CAMBIO_ACEITE_BASICO_NAFTA',
    CAMBIO_ACEITE_BASICO_DIESEL = 'CAMBIO_ACEITE_BASICO_DIESEL',
    CAMBIO_ACEITE_ALTO_RENDIMIENTO_NAFTA = 'CAMBIO_ACEITE_ALTO_RENDIMIENTO_NAFTA',
    CAMBIO_ACEITE_ALTO_RENDIMIENTO_DIESEL = 'CAMBIO_ACEITE_ALTO_RENDIMIENTO_DIESEL'
  }